# Base configs
baseurl: "https://ramonalvar.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Ramon Alvarez"
subtitle: "Experience beauty with your naked eyes!"
author: "Ramon Alvarez"
header:
 title: "Photography"
 subtitle: "by Ramon Alvarez"
footer:
 name: "¡Hola!, me llamo Ramon Alvarez"
 bio: "Soy un fotógrafo especializado en fotografia de moda y artistica. Realizo books y otros trabajos. No dudes en preguntar!"
 github: "¿Quieres ver el código de mi web? Pásate por <a href=\"https://github.com/ramonalvar/photography\"></a> ;)"
social_urls:
  facebook: "https://www.facebook.com/profile.php?id=100013275012558"
  instagram: "https://www.instagram.com/ramonalvarez.photo/"
